OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
RGBLIGHT_ANIMATIONS = no
WPM_ENABLE = no
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = no
RAW_ENABLE = yes
CONSOLE_ENABLE = no
BLUETOOTH_ENABLE = no
EXTRAFLAGS += -flto
