OLED_DRIVER_ENABLE = no   # Enables the use of OLED displays
ENCODER_ENABLE = no       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
RGBLIGHT_ANIMATIONS = yes
#WPM_ENABLE = no
MOUSEKEY_ENABLE = yes
#TAP_DANCE_ENABLE = no
EXTRAFLAGS += -flto
RAW_ENABLE = yes
